"""Добавить поле password в таблицу users

Revision ID: 37fccee82873
Revises: 241a340694f3
Create Date: 2025-06-28 18:46:14.254303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fccee82873'
down_revision: Union[str, None] = '241a340694f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.execute("UPDATE users SET password='default_password'")  # временное значение
    op.alter_column('users', 'password', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
